FROM node:20-alpine
WORKDIR /app
ENV PNPM_HOME=/usr/local/share/pnpm
ENV PATH=$PNPM_HOME:$PATH
RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile --prod

COPY tsconfig.json ./
COPY trigger.config.ts ./
# se seu código estiver em apps/src, troque para: COPY apps/src ./src
COPY src ./src

# produção (NÃO usar "dev")
CMD ["pnpm","dlx","trigger.dev@latest","start","--log-level","info"]